### ISSUE TITLE
UPnP Error 800 received

### ISSUE THREAD

**Issue by Steve0212a** [avantrec/soco-cli#80]
I am trying to add and play a spotify link.  I cannot get it to work.  I even tried using the sharelink directly from the documentation (shown below).  The speaker name "den" works for me for other things like play/pause.

```
sonos den sharelink https://open.spotify.com/track/6cpcorzV5cmVjBsuAXq4wD
Error: Unable to add sharelink to queue: UPnP Error 800 received:  from 10.1.9.194
```

Any ideas on what would cause UPnP Error 800?

Thanks

**Comment by pwt** [comment]
Hi Steve:

This is a Sonos issue, or at least it's something they've changed recently in S2. Take a look at https://github.com/SoCo/SoCo/issues/969.

The reporter suggests that this has been fixed via a Sonos update, but my S2 device (software version `82.2-59204 (16.5)`) still exhibits the error. I'm waiting to see if they subsequently fix it or if it's something they've permanently and deliberately broken.

**Comment by Steve0212a** [comment]
I too have 16.5 exhibiting the error.  Hope it is fixed...

**Comment by pwt** [comment]
Sonos appears to have fixed this in S2/16.5.1.

**Comment by Steve0212a** [comment]
I am still getting the error on 16.5.1...

From about my system:
```
Play:1: Den
Serial Number: xxxxxx
Sonos OS: S2
Version: 16.5.1 (build 82360160)
Hardware Version: 1.8.3.7-1.0
Series ID: A101
IP Address: 10.1.9.194
WM: 1
OTP: 
```

```
sonos den sharelink https://open.spotify.com/track/7snQQk1zcKl8gZ92AnueZW
Error: Unable to add sharelink to queue: UPnP Error 800 received:  from 10.1.9.194
```

**Comment by Steve0212a** [comment]
Understood.  I will update this issue if they fix it.  Thanks

**Comment by jeffreykuiken** [comment]
I'm having the same issue. Started with the 82.2-59204 update to my Sonos speakers, and still happens on the most recent version 82.3-60160.

I'm seeing this issue not just when trying to directly play a ShareLink, but also when I'm attempting to play a favorite that's from Spotify (i.e. `sonos abc play_favorite MyPlaylist`).

**Comment by pwt** [comment]
> I'm having the same issue. Started with the 82.2-59204 update to my Sonos speakers, and still happens on the most recent version 82.3-60160.
> 
> I'm seeing this issue not just when trying to directly play a ShareLink, but also when I'm attempting to play a favorite that's from Spotify (i.e. `sonos abc play_favorite MyPlaylist`).

Thanks. I've updated the issue title. I think we'll need to wait and see if Sonos fixes this.

**Comment by jeffreykuiken** [comment]
I've noticed that recently, starting Spotify playback using a ShareLink started working again. Starting playback of a Spotify favorite is still returning the same error. My speaker is on the most recent 83.1-62052 OS version.
